version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: novi_db
        MYSQL_USER: decadence
        MYSQL_PASSWORD: decadence